### ISSUE TITLE
Notice about mobile devices.

### ISSUE THREAD

**Issue by MikuAuahDark** [novemberisms/brinevector#2]
While this library gives very high performance boost on desktop platforms, this will be very slow in mobile platforms because JIT compiler is not enabled by default there (around 20x slower than plain table).

A strong notice about this in the readme would be good.

**Comment by flamendless** [comment]
Thanks. I'll put a notice on my fork of the lib for vector3D

**Comment by novemberisms** [comment]
Thanks for the heads-up! I updated the readme to have a warning not to use it for mobile applications under the "Compatibility" section.
